apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.petclinic.configmap.name }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
data:
  DATABASE: {{ .Values.petclinic.configmap.database }}