apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.petclinic.deployment.name }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
    tier: backend
spec:
  replicas: {{ .Values.petclinic.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "petclinic-chart.selectorLabels" . | nindent 6 }}
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "petclinic-chart.selectorLabels" . | nindent 8 }}
        tier: backend
    spec:
      containers:
        - name: {{ .Values.petclinic.container.name }}
          image: {{ .Values.petclinic.image.name }}:{{ .Values.petclinic.image.tag }}
          imagePullPolicy: {{ .Values.petclinic.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            {{- toYaml .Values.petclinic.container.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.petclinic.service.name }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
    tier: backend
spec:
  ports:
    - port: {{ .Values.petclinic.service.port }}
      protocol: TCP
      nodePort: {{ .Values.petclinic.service.nodePort }}
      targetPort: {{ .Values.petclinic.service.targetPort }}
      name: {{ .Values.petclinic.service.name }}
  type: NodePort
  selector:
    {{- include "petclinic-chart.selectorLabels" . | nindent 4 }}
    tier: backend