petclinic:
  deployment:
    name: petclinic-deployment
    replicas: 3
  container:
    name: petclinic-container
    resources: { }
  service:
    name: petclinic-service
    port: 8080
    targetPort: 8080
    nodePort: 30000
  image:
    name: petclinic
    tag: latest
    pullPolicy: Never
  configmap:
    name: petclinic-config
    database: h2

ingress:
  enabled: true
  name: petclinic-ingress
  rules:
    - host: petclinic.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            serviceName: petclinic-service
            portNumber: 8080