// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.rntgroup.rpc.protocols.grpc.proto;

public final class Messaging {
  private Messaging() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messaging_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messaging_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017messaging.proto\022\tmessaging\"b\n\016RequestM" +
      "essage\022\035\n\004Type\030\001 \001(\0162\017.messaging.Type\022\017\n" +
      "\007message\030\002 \001(\t\022\016\n\006sender\030\003 \001(\t\022\020\n\010receiv" +
      "er\030\004 \001(\t\"c\n\017ResponseMessage\022\035\n\004Type\030\001 \001(" +
      "\0162\017.messaging.Type\022\017\n\007message\030\002 \001(\t\022\016\n\006s" +
      "ender\030\003 \001(\t\022\020\n\010receiver\030\004 \001(\t*J\n\004Type\022\007\n" +
      "\003SMS\020\000\022\n\n\006LETTER\020\001\022\n\n\006PIGEON\020\002\022\007\n\003ICQ\020\003\022" +
      "\016\n\nTELEPATHIC\020\004\022\010\n\004WILL\020\0052X\n\020MessagingSe" +
      "rvice\022D\n\013sendMessage\022\031.messaging.Request" +
      "Message\032\032.messaging.ResponseMessageB1\n%c",
      "om.rntgroup.rpc.protocols.grpc.protoP\001Z\006" +
      "proto/b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messaging_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messaging_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messaging_RequestMessage_descriptor,
        new String[] { "Type", "Message", "Sender", "Receiver", });
    internal_static_messaging_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messaging_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messaging_ResponseMessage_descriptor,
        new String[] { "Type", "Message", "Sender", "Receiver", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
