// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.rntgroup.rpc.protocols.grpc.proto;

/**
 * Protobuf enum {@code messaging.Type}
 */
public enum Type
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SMS = 0;</code>
   */
  SMS(0),
  /**
   * <code>LETTER = 1;</code>
   */
  LETTER(1),
  /**
   * <code>PIGEON = 2;</code>
   */
  PIGEON(2),
  /**
   * <code>ICQ = 3;</code>
   */
  ICQ(3),
  /**
   * <code>TELEPATHIC = 4;</code>
   */
  TELEPATHIC(4),
  /**
   * <code>WILL = 5;</code>
   */
  WILL(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SMS = 0;</code>
   */
  public static final int SMS_VALUE = 0;
  /**
   * <code>LETTER = 1;</code>
   */
  public static final int LETTER_VALUE = 1;
  /**
   * <code>PIGEON = 2;</code>
   */
  public static final int PIGEON_VALUE = 2;
  /**
   * <code>ICQ = 3;</code>
   */
  public static final int ICQ_VALUE = 3;
  /**
   * <code>TELEPATHIC = 4;</code>
   */
  public static final int TELEPATHIC_VALUE = 4;
  /**
   * <code>WILL = 5;</code>
   */
  public static final int WILL_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static Type valueOf(int value) {
    return forNumber(value);
  }

  public static Type forNumber(int value) {
    switch (value) {
      case 0: return SMS;
      case 1: return LETTER;
      case 2: return PIGEON;
      case 3: return ICQ;
      case 4: return TELEPATHIC;
      case 5: return WILL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Type>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Type> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Type>() {
          public Type findValueByNumber(int number) {
            return Type.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Messaging.getDescriptor().getEnumTypes().get(0);
  }

  private static final Type[] VALUES = values();

  public static Type valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:messaging.Type)
}

