/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rntgroup.rpc.protocols.avro.schema;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Genre {
  HORROR, FANTASY, SCIENCE_FICTION, MYSTIC, ROMANTIC, DRAMA, FAIRYTALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Genre\",\"namespace\":\"com.rntgroup.rpc.protocols.avro.schema\",\"symbols\":[\"HORROR\",\"FANTASY\",\"SCIENCE_FICTION\",\"MYSTIC\",\"ROMANTIC\",\"DRAMA\",\"FAIRYTALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
