spring:
  application:
    name: local-grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'localhost:9099'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext