spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: group-id
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.rntgroup.*

scheduling:
  producer: 5000