spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

messaging:
  broker: activemq
  host: 127.0.0.1
  port: 61616
  user: admin
  password: adminactivemq